version: '3'
services:
  app:
    build: docker/php
    networks:
      - test
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.12-alpine
    networks:
      - test
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    networks:
      - test
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2_agora
      MYSQL_USER: yii2_agora
      MYSQL_PASSWORD: 123456

networks:
  test:
    external:
      name: nat