#!/bin/bash
php yii migrate --migrationPath=@yii/rbac/migrations
php yii migrate
php yii migrate --migrationPath=@yii/log/migrations
php yii migrate --migrationPath=@vendor/intermundia/yii2-mailer/migrations