export const SET_TIMELINE_LOADING = 'timeline/SET_TIMELINE_LOADING';
export const SHOW_TIMELINE_MODAL = 'timeline/SHOW_TIMELINE_MODAL';
export const HIDE_TIMELINE_MODAL = 'timeline/HIDE_TIMELINE_MODAL';
export const SET_TIMELINE_DATA = 'timeline/SET_TIMELINE_DATA';