export const SHOW_WORKSPACE_MODAL = 'workspace/SHOW_WORKSPACE_MODAL';
export const HIDE_WORKSPACE_MODAL = 'workspace/HIDE_WORKSPACE_MODAL';
export const GET_USER_WORKSPACES = 'workspace/GET_USER_WORKSPACES';
export const WORKSPACE_DELETED = 'workspace/WORKSPACE_DELETED';
