import './bootstrap-vue';
import './font-awesome';
import './vee-validate';
import './confirm-dialog';
import './alert-dialog';
import './notification';
import './toaster';
import './ckeditor';
import './vue-clipboard2';
