export const SET_COUNTRIES_LOADING = 'setup/SET_COUNTRIES_LOADING';
export const SET_COUNTRIES = 'setup/SET_COUNTRIES';
export const SHOW_COUNTRY_MODAL = 'setup/SHOW_COUNTRY_MODAL';
export const HIDE_COUNTRY_MODAL = 'setup/HIDE_COUNTRY_MODAL';
export const SET_DEPARTMENTS_LOADING = 'setup/SET_DEPARTMENTS_LOADING';
export const SET_DEPARTMENTS = 'setup/SET_DEPARTMENTS';
export const SHOW_DEPARTMENT_MODAL = 'setup/SHOW_DEPARTMENT_MODAL';
export const HIDE_DEPARTMENT_MODAL = 'setup/HIDE_DEPARTMENT_MODAL';
